package com.example.mr13.belajarbahasajawa;


import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.RecyclerView;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Menu;
import android.widget.Adapter;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ListView;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;


public class activity_satu extends AppCompatActivity {
    private ListView lv;

    ArrayAdapter<String> adapter;
    EditText inputSearch;

    ArrayList<HashMap<String,String>> itemList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_satu);

        getSupportActionBar().setTitle("Kosakata");;
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        String  item[] = {
                " aba = - =  dhawuh = perintah  ",
                " abah-abah = - = kambil = pelana ",
                " abang = abrit = - =  merah ",
                " abot = awrat = - =  berat ",
                " adêg = - =  jumênêng=  berdiri ",
                " adang = bêthak = - =  menanak nasi ",
                " adhêm = asrêp = - =  dingin ",
                " adhêp = ajêng = - =  hadap ",
                " adhi = - =  rayi  =  adik ",
                " adoh = têbih = - =  jauh ",
                " adol = sade = - =  jual ",
                " adon = abên = - =  sabung ",
                " adu =  abên = - =  menyabung ",
                " adus = - = siram = mandi ",
                " agama = agami = - = agama ",
                " age =  enggal = - = cepat ",
                " agek = sawêg = - = baru saja ",
                " aja =  sampun = - = jangan ",
                " ajang = ajang = ambêng = tempat nasi ",
                " aji =  aos = - = nilai, harga, martabat ",
                " aju =  ajêng = - =  maju ",
                " akeh = kathah = - =  banyak ",
                " akon = akên = dhawuh = suruh ",
                " aksama = aksami = - =  ampun, maaf ",
                " aku =  kula = dalêm = saya ",
                " aku, ngaku = aken = - =mengaku ",
                " ala =  awon = - = buruk, jelek ",
                " alangan = pambêngan=     = halangan ",
                " alas = wana = - = hutan ",
                " ali-ali = sêsupe = - =  cincin ",
                " alih = pindhah = - =  pindah ",
                " alis = - =  imba  =  alis ",
                " amarga = amargi = - =  karena ",
                " amba = wiyar = - =  lebar ",
                " ambu = ambêt = ganda = bau ",
                " ambung = - =  aras = cium ",
                " amek = mêndhêt = - =  ambil ",
                " amêrga = amêrgi = - =  karena ",
                " amit = - =  nuwun sewu = minta maaf ",
                " ampir = - =  pinarak = singgah ",
                " ana =  wonten = - =ada ",
                " anak = anak, lare = putra = anak ",
                " andêl = pitados = - =  percaya ",
                " angel = awrat = - =  sulit ",
                " anggêr = saugêr = - =  asalkan ",
                " angkat = bidhal = tindhak, jêngkar = pergi ",
                " anggo = anggê = agêm = pakai ",
                " angon = angen = - =  menggembala ",
                " ani-ani = pugut = - =  ani-ani (alat penuai padi) ",
                " anom = ênem = - =  muda ",
                " antara = antawis = - =  antara ",
                " anut = tumut = dherek = ikut ",
                " anyar = enggal = - =  baru ",
                " apa =  punapa = - =  apa ",
                " apik = sae = - = baik, bagus ",
                " apura = apuntên = - = maaf ",
                " arah = angkah = - = maksud, tujuan ",
                " aran = nama = asma = nama ",
                " arang = awis = - = jrang ",
                " arep = ajêng = kêrsa = mau ",
                " arti = artos = - = makna ",
                " asor = awon = andhap = rendah ",
                " asu = sêgawon = - = anjing ",
                " ati = manah = penggalih = hati ",
                " atop = - = sêgu = tersendawa ",
                " atur = - = unjuk = beri ",
                " awak = badan = salira = badan, tubuh ",
                " awan = siyang = - = siang ",
                " aweh = nyukani = maringi = beri ",
                " ayake = mbok mênawi = - = barangkali ",
                " ayo = mangga = - = marilah ",
                " bacut = lajêng = - = kemudian, lantas ",
                " bae = kemawon = - = hanya ",
                " bakal = badhe = - = akan ",
                " baki = - = panadhahan = nampan ",
                " bako = sata = - = tembakau ",
                " baku = bakên = - = pokok ",
                " bali = wangsul = kondur = kembali ",
                " balung = - = tosan = tulang ",
                " banda = - = dipunbêsta = dibelenggu ",
                " bangêt = sangêt = - = sangat ",
                " bangga = banggi = - = tidak menurut ",
                " bangkekan = - = wangkingan = pinggang ",
                " banjir = bêna = - = banjir ",
                " banjur = lajêng = - = lalu, setelah itu ",
                " bantal = - = kajang = bantal ",
                " banyu = toya = - = air ",
                " bapa, bapak = rama = - = bapak ",
                " barêng = sarêng = - = bersama ",
                " barêp = pambajêng = pambayun = sulung ",
                " bata = banon = - = batu bata ",
                " bathik = sêrat = - = batik ",
                " bathuk = - = palarapan = dahi ",
                " batin = batos = - = batin ",
                " batur = rencang = abdi = hamba, pembantu ",
                " bebek = kambangan = - = itik ",
                " beda = bêntên = - = beda ",
                " ben, karêben = kajêngipun = kêrsanipun = biarlah ",
                " besuk = benjing = - = besuk ",
                " bêbêd = - = nyamping = jarik (untuk pria) ",
                " bêbuwang = bêbucal = bobotan = buang air besar ",
                " bêcik = sae = - = baik ",
                " bêdhil = sênjata = - = senjata ",
                " bêdudan = - = watangan = pipa rokok ",
                " bênêr = lêrês = kasinggihan = benar, betul ",
                " bêngi = dalu = - = malam ",
                " bêras = wos = - = beras ",
                " bisa = sagêd = - = dapat, bisa ",
                " biyen = riyin = rumiyin = dulu ",
                " biyung = - = ibu = ibu ",
                " bobot = wawratipun = - = beratnya ",
                " bocah = lare = - = anak ",
                " bojo = semah = garwa = suami/istri ",
                " bokong = - = pocong = bokong ",
                " bolah = bênang = - = benang ",
                " boreh = - = konyoh = bedak ",
                " brengos = - = rawis = kumis ",
                " bubar = bibar = - = selesai ",
                " bubrah = bibrah = - = rusak ",
                " budi = manah = pênggalih = budi, pikiran, akal ",
                " budhal = bidhal = - = berangkat ",
                " bukak = bikak = - = buka ",
                " bungah = bingah = rêna = gembira ",
                " buri = wingking = - = belakang ",
                " buru = bujêng = - = buru ",
                " buruh = bêrah = - = buruh, pekerja ",
                " buta = danawa = - = raksasa ",
                " butuh = bêtah = - = butuh ",
                " buwang = bucal = - = buang ",
                " buyar = rampung = rampung = selesai ",
                " calathu = wicantên = ngandika = berbicara ",
                " cangkêm = lesan = tutuk = mulut ",
                " cangkir = - = tuwung = cangkir ",
                " carita = cariyos = - = cerita ",
                " caturan = wicantên = ngendikan = omongan ",
                " cawis = cawisaken = caosaken = disiapkan ",
                " celeng = andhapan = - = babi hutan ",
                " cewok = - = cawik = bercebok ",
                " cêdhak = cêlak = - = dekat ",
                " cêkêl = cêpêng = dipunasta = dipegang ",
                " cêndhek = andhap = - = pendek, rendah ",
                " cêngêl = - = griwa = tengkuk ",
                " cêpêt = enggal = - = cepat ",
                " cilik = alit = - = kecil ",
                " coba = cobi = - = coba ",
                " crita = criyos = - = cerita ",
                " cucul = - = lukar = lepas baju ",
                " cukup = cêkap = - = cukup ",
                " cukur = pangkas = paras = bercukur ",
                " cumbana = - = saresmi = setubuh ",
                " cundhuk = - = sangsangan = sunting ",
                " dadah = - = ginda = pijit ",
                " dadi = dados = - = jadi ",
                " dagang = gramen = - = dagang ",
                " dalan = radinan = margi = jalan ",
                " dandan = dandos = busana = berhias ",
                " darma = darmi = - = pelaksanaan tugas ",
                " dawa = panjang = - = panjang ",
                " deleh = suka = paring = taruh ",
                " desa = dhusun = - = desa ",
                " dêlêng = tingal = priksa = lihat ",
                " dêrma = drêma = - = amal ",
                " dhadha = - = jaja = dada ",
                " dhayoh = tamu = - = tamu ",
                " dhêk = kala = - = pada waktu ",
                " dhêmên = rêmên = - = senang ",
                " dhêngkul = - = jêngku = lutut ",
                " dhêngêr = sumêrêp = priksa = tahu, mengerti ",
                " dhewe = piyambak = - = sendiri ",
                " dhek = kala = nalika = ketika ",
                " dhisik = rumiyin = - = dahulu ",
                " dhun = mandhap = - = turun ",
                " dhuwit = yatra = arta = uang ",
                " dhuwur = inggil = luhur = tinggi ",
                " dina = dintên = - = hari ",
                " diyan = dilah = - = lampu ",
                " dlamakan = - = samparan =  ",
                " dluwang = dlancang = - = kertas ",
                " dodod = - = kampuh = dodot ",
                " dokok = dekek = paring = taruh ",
                " dol = sade = - = jual ",
                " dolan = - = amêng-amêng = main-main ",
                " dom = jarum = - = jarum ",
                " doyan = purun = kêrsa = mau ",
                " driji = - = racikan = jari ",
                " du, ngedu = ngaben = - = mengadu ",
                " dudu = sanes = - = bukan ",
                " duga = dugi = - = duga ",
                " dulang = ndulang = ndahari = menyuapi ",
                " dulur = dherek = santana = saudara ",
                " durung = dereng = - = belum ",
                " duwe = gadhah = kagungan = punya ",
                " edan = ewah = gêrah ewah = gila ",
                " elek = awon = - = jelek ",
                " eling = emut = - = ingat ",
                " elmu = elmi = - = ilmu ",
                " elu = tumut = ndherek = ikut ",
                " enak = eca = - = enak ",
                " epek-epek = - = tapak asta =  ",
                " etung = etang = - = hitung ",
                " esuk = enjing = enjing = pagi ",
                " ewuh = êwêd = - = repot ",
                " êdoh = nêbih = - = menjauh ",
                " êlih = mindah = - = memindah ",
                " êluh = - = waspa = airmata ",
                " êmas = jene = - = emas ",
                " êmbah = simbah = êyang = kakek ",
                " êmbuh = kilap = duka = tidak tahu ",
                " êmbun-êmbun = sundhulan = - = ubun-ubun ",
                " êmbok = - = ibu = ibu ",
                " êmoh = botên purun = boten kêrsa = tidak mau ",
                " êmot = ngêwrat = - = memuat ",
                " êndêm = - = wuru = mabuk ",
                " êndhas = sirah = mustaka = kepala ",
                " êndhêg = kendêl = - = henti ",
                " êndhog = tigan = - = telur ",
                " êndi = pundi = - = mana ",
                " enêng = mendêl = - = diam ",
                " êner = lêrês = - = arah ",
                " ênggo = êngge = agêm = pakai ",
                " ênggon = ênggen = - = tempat ",
                " ênom = ênem = - = muda ",
                " êntas = nêmbe = - = baru saja ",
                " êntek = telas = - = habis ",
                " ênteni = entosi = rantosi = tunggu ",
                " êntut = - = sarib = kentut ",
                " ênyang = awis = - = tawar ",
                " êpêk = pêndhêt = pundhut = ambil ",
                " gadhe = nggantos = - = menggadaikan ",
                " gadhuh = - = ngampil = meminjam ",
                " gajah = liman = - = gajah ",
                " galo = mênika lo = - = itulah ",
                " gaman = dêdamêl = - = senjata tajam ",
                " gamêlan = gangsa = - = gamelan ",
                " gampang = gampil = - = mudah ",
                " ganêp = jangkêp = - = lengkap ",
                " ganti = gantos = - = ganti ",
                " gati = gatos = - = panting ",
                " gawa = bekta = asta = bawa ",
                " gawe = damel = ngasta = membuat ",
                " geneya = kenging mênapa = - = mengapa ",
                " gêbug = gêbag = - = pukul ",
                " gêdhang = pisang = - = pisang ",
                " gêdhe = agêng = - = besar ",
                " gêdhen = agengan = - = serba banyak ",
                " gêgêr = - = pêngkêran = punggung ",
                " gêlang = - = binggêl = gelang ",
                " gêlêm = purun = kêrsa = mau ",
                " gêlung = - = ukêl = gelung ",
                " gêmak = puyuh = - = burung puyuh ",
                " gêmati = gêmatos = - = merawat dengan baik ",
                " gêndhuk = - = nini = putri ",
                " gênêp = jangkêp = - = lengkap ",
                " gêni = latu = - = api ",
                " gênti = gêntos = - = ganti ",
                " gêring = kêra = susut = kurus ",
                " gêtih = rah = ludira = darah ",
                " githok = - = griwa = tengkuk ",
                " glugu = glêga = - = pohon kelapa ",
                " gocek = cêpêng = - = memegang ",
                " godheg = - = gumbala = cambang ",
                " godhong = ron = - = daun ",
                " golek = pados = - = cari ",
                " guroh = dora = - = bohong ",
                " gugah = gigah = wungu = bangun ",
                " gugat = gigat = - = gugat ",
                " gugu = gêga = ngestokaken = menurut ",
                " gula = gêndhis = - = gula ",
                " gulu = - = jangga = leher ",
                " gumati = gumatos = - = merawat dengan baik ",
                " guna = gina = - = guna ",
                " gunêm = ginêm = ngêndika = berbicara ",
                " gunung = rêdi = - = gunung ",
                " gusi = - = wingkisan = gusi ",
                " guyu = gujeng = - = tawa ",
                " icip = dipunincip = dipunkêdhapi = dicicip ",
                " idêp = - = ibing = bulu mata ",
                " idêr = - = pêpara = berkeliling ",
                " idu = - = kêcoh = ludah ",
                " iga = - = unusan = tulang rusuk ",
                " ijo = ijêm = - = hijau ",
                " ijol = lintu = - = tukar ",
                " ika = mênika = - = itu ",
                " ikêt = - = dhêstar = ikat kepala ",
                " iki = niki = punika = ini ",
                " iku = mênika = - = itu ",
                " ilmu = elmu = - = ilmu ",
                " ilang = ical = - = hilang ",
                " ilat = - = lidah = lidah ",
                " ilo = - = paningalan = cermin ",
                " ilu = tumut = ndherek = ikut ",
                " imbuh = imbet, ngimbet = - = peram, memeram ",
                " imbon = imbêtan = - = peraman ",
                " imbuh = imbêt = tanduk = tambah ",
                " impi = supêna = - = impi ",
                " inêp = sipêng = - = inap ",
                " inggat = - = lolos = pergi tanpa pamit ",
                " ingu = ingah = - = piara, pelihara ",
                " intên = sela = - = intan ",
                " irêng = cêmêng = - = hitam ",
                " iring = - = dherekaken = diiringkan ",
                " irung = - = grana = hidung ",
                " isa = saged = - = bisa ",
                " isin = lingsem = - = malu ",
                " isih = taksih = - = masih ",
                " ising = bêbucal = kêbêlêt, bobotan = buang air besar ",
                " isor = andhap = - = bawah ",
                " iwak = ulam = - = ikan ",
                " jaba = jawi = - = luar ",
                " jaga = jagi = reksa = jaga ",
                " jago = sawung = - = jago, calon ",
                " jala = jambêt = - = jala, jaring ",
                " jalu = jalu, panja = - = taji ",
                " jaluk = nedi = nyuwun = minta ",
                " jam = jam, pukul = - = jam ",
                " jambe = wohan = - = pinang ",
                " jambu = jambêt = - = jambu ",
                " jamu = jampi = loloh, usada = jamu ",
                " janggut = - = kêthêkan = dagu ",
                " jaran = kapal = titihan, turangga = kuda ",
                " jare = cariyosipun = ngêndikanipun = katanya ",
                " jarit = sinjang = nyamping = kain batik ",
                " jarwa = jarwi = - = artinya ",
                " jati = jatos = - = jati, nyata, betul ",
                " jawa = jawi = - = suku jawa ",
                " jêmbar = wiyar = - = luas ",
                " jênat = - = suwargi = orang yang sudah mati ",
                " jênêng = nama = asma = nama ",
                " jênggot = - = gumbala = janggut ",
                " jero = lêbêt = - = dalam ",
                " jêruk = jêram = - = jeruk ",
                " jisim = - = layon = mayat ",
                " joged = - = beksa = tari ",
                " jungkat = serat = pethat = sisir ",
                " jupuk = pendhet = pundhut = ambil ",
                " kabêcikan = kêsaenan = - = kebaikan ",
                " kabeh = sedaya = sedanten = semua ",
                " kacamata = kacamripat = kacatingal = kacamata ",
                " kacek = kaot = - = beda, selisih ",
                " kacu = - = usap asta = sapu tangan ",
                " kadhêmên = kasrêpên = - = kedinginan ",
                " kadohan = kêtêbihên = - = terlalu jauh ",
                " kae = punika = - = itu ",
                " kaget = - = kejot = terkejut ",
                " kagetan = kêjotan = - = mudah terkejut ",
                " kajaba = kêjawi = - = kecuali ",
                " kajawan = kajawen = - = wilayahnya orang jawa ",
                " kaji = ngaos = - = mengaji ",
                " kakang = - = kangmas, raka = kakak laki-laki ",
                " kakehan = kêkathahên = - = kebanyakan ",
                " kaku = kaken = - = kaku ",
                " kalah = kawon = kasoran = kalah ",
                " kali = lepen = - = sungai ",
                " kalumrahan = kalimrahan = - = kebiasaan ",
                " kalung = - = sangsangan = kalung ",
                " kalungguhan = - = kalênggahan = pangkat, kedudukan ",
                " kaluputan = kalêpatan = - = kesalahan ",
                " kambil = klapa = - = kelapa ",
                " kambu = kambet = - = tercium baunya ",
                " kamitua = kamisepuh = - = pimpinan desa ",
                " kamot = kawrat = - = muat ",
                " kana = ngrika = - = sana ",
                " kanca = rencang = - = teman ",
                " kandha = sanjang = matur = berkata ",
                " kangên = - = kapang, oneng = rindu ",
                " kangêrten = kangêrtosan = - = diketahui ",
                " kanggo = kangge = kagem = buat ",
                " kanti = kantos = - = hingga, sampai ",
                " kantên = kantosan = - = penyabar ",
                " kapan = mbenjing menapa = - = kapan ",
                " kapiran = kapinten = - = tidak terawat ",
                " kara-kara = kawis-kawis = - = halangan ",
                " karangên = kawisên = - = terlalu jarang ",
                " karêben = kajengipun = - = biar saja, supaya ",
                " karêp = kajêng = kersa = niat, maksud ",
                " karêpe = kajêngipun = kêrsanipun = maksudnya ",
                " kari = kantun = - = tertinggal ",
                " karo = kalih = - = kedua ",
                " karo = kaliyan = - = dengan ",
                " kartu = kêrtos = - = kartu ",
                " karuhan = kantênan = - = tentu, jelas ",
                " kasoran = kawonan = kandhapan = kalah ",
                " kathok = sruwal = lancingan = celana ",
                " kathokan = sruwalan = lancingan = bercelana ",
                " katon = katingal = - = dapat dilihat ",
                " kaya = kados = - = seperti ",
                " kayu = kajêng = - = batang pohon ",
                " kawanên = kêsiangan = - = kesiangan ",
                " kawêngên = kêdalon = - = kêmalaman ",
                " kawigaten = kawigatosan = - = perhatian ",
                " kawruh = sêsêrêpan = - = pengetahuan ",
                " kelangan = kecalan = - = kehilangan ",
                " kelingan = kemutan = - = teringat ",
                " kempol = - = wengkelan = betis ",
                " kene = riki = - = sini ",
                " keren = kantunan = - = sisa ",
                " keri = kantun = - = tertinggal ",
                " kesuk = sakenjing = - = sepanjang pagi ",
                " ketok = asring = - = kelihatan ",
                " kewuhan = kewêdan = - = sangat segan ",
                " kê = kaping = - = kebatinan ",
                " kêbacut = kelajeng = - = terlanjur ",
                " kêbangêtên = kêsangêtên = - = keterlaluan ",
                " kêbanyon = kêtoyan = - = terairi (sawah) ",
                " kêbatinan = kêbatosan = - = kebati ",
                " kêbênêr = kêlêrês = - = kebetulan ",
                " kêbiren = kêbincihan = - = hewan yang dikebiri ",
                " kêbiri = dipunkêbiri = - = dimandulkan ",
                " kêbo = maesa = - = kerbau ",
                " kêbocahên = kêlaren = - = kekanak-kanakan ",
                " kêbutuhan = kabêtahan = - = kebutuhan ",
                " kêcilikên = kalitên = - = terlalu kecil ",
                " kêdadeyan = kêdadosan = - = kejadian ",
                " kêdhep = - = kejep = kejap ",
                " kêjaba = kêjawi = - = kecuali ",
                " kêkarêpane = kêkajênganipun = - = kehendak ",
                " kêkêmbangan = sêsêkaran = - = bunga-bungaan ",
                " kêkêmon = - = kêkêmbêngan = berkumur ",
                " kêlairan = wêdalan = wiyosan = kelahiran ",
                " kêlakon = kêlampahan = - = terlaksana ",
                " kêlalen = kêsupen = - = terlupa ",
                " kêlar, kuwat = kuwawi = - = kuat ",
                " kêlaran = kêsakitan = - = kesakitan ",
                " kêlalen = kêsupen = kalimêngan = terlupa ",
                " kêluron = - = têrag = keguguran ",
                " kêmalingan = kêpandungan = - = kecurian ",
                " kêmbang = sêkar = - = bunga ",
                " kêmênyan = sela = - = kemenyan ",
                " kêmu = - = kembeng = kumur ",
                " kêmul = - = singêb = selimut ",
                " kêna = kenging = - = boleh ",
                " kêndêl = purun = - = berani ",
                " kêndhekên = kandhapan = - = sangat pendek ",
                " kêntekan = kêtêlasan = - = kehabisan ",
                " kêpaten = kêpêjahan = kêsedan = kematian ",
                " kêpêntut = - = kêsarib = kentut ",
                " kêpriye = kados pundi = - = bagaimana ",
                " kêpung = kêpang = - = dikelilingi ",
                " kêrêp = asring = - = sering ",
                " kêris = dhuwung = wangkkingan = keris ",
                " kêsêl = sayah = - = lelah ",
                " kêsusu = kêsêsa = - = tergesa-gesa ",
                " kêsuwen = kvdangon = - = terlalu lama ",
                " kêtara = kêtawis = - = kentara ",
                " kêtêkan = kêdhatêngan = krawuhan = didatangi ",
                " kêtêmu = kêpanggih = - = bertemu ",
                " kêthek = - = rewanda = kera ",
                " kêwêngen = kêdalon = - = kemalaman ",
                " kijing = - = sêkaran = nisan ",
                " kinacek = kinaot = - = istimewa ",
                " kinang = ganten = - = kingang ",
                " kira = kintên = - = kira ",
                " kirim = kintun = - = kirim ",
                " kiyi = mênika = - = ini ",
                " klambi = rasukan = agêman rasukan = baju ",
                " klasa = gêlaran = - = tikar ",
                " kleru = klintu = - = keliru ",
                " klêbu = klêbêt = - = termasuk ",
                " klbon = klêbêtan = - = kemasukan ",
                " klêngêr = - = kantu = pingsan ",
                " klumpuk = klêmpak = - = kumpul ",
                " kobong = kabêsmi = - = kebakar ",
                " kok = sampeyan = panjênêngan = kau ",
                " kodanan = kêjawahan = - = kejawahan ",
                " kongkon = kengken = ngutus = menyuruh ",
                " kono = riku = - = situ ",
                " kowe = sampeyan = panjenengan = kamu ",
                " kramas = - = jamas =  ",
                " krasa = kraos = - = terasa ",
                " krasan = kraosan = - = betah ",
                " kringêt = - = riwe = mandi jamas ",
                " kubur = petak = sarean = kubur ",
                " kuburan = - = pasareyan = makan ",
                " kudu = kêdah = - = harus ",
                " kuku = - = kênaka = kuku ",
                " kukuh = kêkah = - = kokoh ",
                " kulak = kilak = - = membeli untuk dijual ",
                " kulon = kilen = - = barat ",
                " kuluk = - = makutha = mahkota ",
                " kumat = kimat = - = kambuh ",
                " kumbah = girah = - = cuci ",
                " kumpul = kêmpal = - = kumpul ",
                " kuna = kina = - = kuna ",
                " kuning = jêne = - = kuning ",
                " kuping = - = talingan = telinga ",
                " kurang = kirang = - = kurang ",
                " kuru = kêra = - = kurus ",
                " kurung = sêngkêr = - = kurung ",
                " kutha = kitha = - = kota ",
                " kuwasa = kuwaos = - = kuasa ",
                " kuwat/kêlar = kiyat/kuwawi = - = kuat ",
                " kuwatir = kuwatos = - = khawatir ",
                " kuwi = niku = punika = itu ",
                " kumawani = kumawantun = - = terlalu berani ",
                " labuh = labêt = - = berjasa untuk ",
                " ladi = lados = - = layan ",
                " lagi = saweg = nembe = baru saja ",
                " lair = - = miyos = lahir ",
                " laki = semah = garwa, sarêsmi = suami ",
                " laku = lampah = tindak = jalan ",
                " lali = supe = - = lupa ",
                " lama = lami, dangu = - = lama ",
                " lambe = - = lathi = bibir ",
                " lan = kaliyan = - = dan ",
                " lanang = jalêr = - = laki-laki ",
                " landa = landi = - = belanda ",
                " landheyan = - = jêjêran = tangkai tombak ",
                " lara = sakit = gerah = sakit ",
                " larang = awis = - = mahal ",
                " lawang = kontên, kori = - = pintu ",
                " lawas = lami, dangu = - = lama ",
                " lawe = sêlangkung = - = dua puluh lima ",
                " lek = - = wungu = terjaga ",
                " leren = kendêl = - = istirahat ",
                " lêbu = lêbêt = - = dalam ",
                " lêlara = sêsakit = - = penyakit ",
                " lêmah = siti = - = tanah ",
                " lêmu = lêma = - = lêmbut, halus ",
                " lênga = lisah = - = minyak ",
                " lêngên = - = pamênthangan = lengan ",
                " lêstari = lêstantun = - = lestari, abadi ",
                " lima = gangsal = - = lima ",
                " linggih = lênggah = pinarak = duduk ",
                " linuwih = linangkung = - = lebih, luar biasa ",
                " liru = lintu = - = tukar, ganti ",
                " liwat = langkung = miyos = lewat ",
                " liwêt = mbênthak = - = menanak nasi ",
                " lor = ler = - = utara ",
                " loro = kalih = - = dua ",
                " lorodan = lorodan = - = bekas ",
                " lucu = - = cucud = lucu ",
                " luh = - = waspa = air mata ",
                " luku = lujêng = - = bajak ",
                " lulang = cucal = - = kulit ",
                " lumrah = limrah = - = biasa ",
                " lunga = kesah = tindak = pergi ",
                " lungguh = - = lênggah = duduk ",
                " luput = lepat = - = salah, keliru ",
                " luwih = langkung = - = lebih ",
                " maca = maos = - = dilisankan ",
                " macan = - = sima = macan ",
                " madu = mabên = - = bertengkar ",
                " maju = majeng = - = maju ",
                " malam = lilin = - = lilin ",
                " maling = padung = - = pencuri ",
                " mamah = - = nggilut = mengunyah ",
                " mana = mantên = - = sekian ",
                " mandhêg = kendêl = - = berhenti ",
                " maneh = malih = - = lagi ",
                " mangan = nedha = dhahar = makan ",
                " mangkana = makatên = - = demikian ",
                " manuk = pêksi = - = burung ",
                " mara = dhatêng = - = datang ",
                " mari = mantun = dhangan = sembuh ",
                " mata = mripat = paningal, soca = mata ",
                " mati = pejah = seda = meninggal ",
                " mau = wau = - = tadi ",
                " mawa = mawi = - = bara api ",
                " mayit = jisim = layon = jenazah ",
                " melu = tumut = dherek = ikut ",
                " menehi = ngaturi, nyukani = nyaosi, maringi = memberi ",
                " mêlek = - = wungu = terjaga ",
                " mênang = mimpang = - = menang ",
                " mênawa = mênawi = - = jika kalau ",
                " mêngko = mangke = - = nanti ",
                " mênjangan = sangsam = - = sejenis rusa ",
                " mêntas = nêmbe = - = baru saja ",
                " mênyang = dhatêng = - = ke ",
                " mêrga = margi = - = karena ",
                " mêruhi = nyêmêrêpi = - = mengetahui ",
                " mêtu = mêdal = miyos = keluar ",
                " mêtêng = wawrat, mbobot = nggarbini = hamil ",
                " milang = mical = - = menghitung ",
                " minggat = kesah = lolos = melarikan diri ",
                " mlaku = mlampah = tindak = berjalan ",
                " mono = mantên = - = demikian ",
                " mor = kêmpal = - = kumpul ",
                " mori = montên = - = kafan ",
                " mot = wrat = - = muat ",
                " mudhun = mandhap = - = turun ",
                " muga-muga = mugi-mugi = - = mudah-mudahan ",
                " mula = mila = - = memang ",
                " mulang = mucal = - = mengajar ",
                " mulih = mantuk = kondur = pulang ",
                " mumêt = - = puyêng = pusing ",
                " mundhak = mindhak = - = tambah ",
                " mung = namung, naming = - = hanya ",
                " munggah = inggah = - = naik ",
                " mungguh = mênggah = - = mengenai ",
                " mungsuh = mêngsah = - = musuh, lawan ",
                " muni = mungel = - = bersuara ",
                " murah = mirah = - = murah ",
                " muring = - = duka = marah ",
                " mutah = - = luntak = muntah ",
                " mutawatir = mutawantos = - = bahaya ",
                " muwah = miwah = - = dan juga ",
                " nagara = nagari = - = negara ",
                " ndandani = ndandosi = - = membetulkan ",
                " ndelehake = nyukakake = maringake = meletakkan ",
                " ndêdawa = memanjang = - = memperpanjang ",
                " ndêleng = ningali = mriksani = melihat ",
                " ndokokake = ndekekakên = maringakên = meletakkan ",
                " nduweni = nggadahi = - = memiliki ",
                " ngadêk = - = jumênêng = berdiri ",
                " ngadhêp = sowan = marak = menghadap ",
                " ngajeni = ngaosi = - = menghargai ",
                " ngaji = ngaos = - = mengaji ",
                " ngajokakên = ngajêngakên = - = memajukan ",
                " ngakoni = ngakêni = - = mengakui ",
                " ngaku = ngakên = - = mengaku ",
                " ngalangi = mambêngi = - = menghalangi ",
                " ngalor = ngaler = - = ke utara ",
                " ngambakake = miyarakên = - = meluaskan ",
                " ngambu = ngambêt = - = membau ",
                " ngambung = - = ngaras = mencium ",
                " nganakake = ngawontênakên = - = mêngadakan ",
                " nganti = ngantos = - = sampai ",
                " nganyang = ngawis = - = menawar ",
                " ngapura = ngapuntên = - = memaafkan ",
                " ngarani = mastani = - = menyebut ",
                " ngarêp = ngajêng = - = di depan ",
                " ngasor = ngawon = - = mengalah ",
                " ngawaki = - = nyêlirani = melakukan sendiri ",
                " ngelingi = ngemuti = - = mengingat ",
                " ngêndhêgake = ngêndêlake = - = menghentikan ",
                " ngendhog = nigan = - = bertelur ",
                " ngenger = - = ngabdi = mengabdi ",
                " nêmpuh = nêmpah = - = nempuh ",
                " nêsu = srêngên = duka = marah ",
                " ngêboti = ngawrati = - = lebih ",
                " ngêlak = - = salit = haus ",
                " ngêlu = - = puyêng = pusing ",
                " ngêpekake = mêndhêtake = mundhutake = mengambilkan ",
                " ngêrti = ngêrtos = priksa = tahu ",
                " nggadhuhi = - = ngampili = meminjami ",
                " ngganti = nggantos = - = mengganti ",
                " nggawa = bêkta = - = membawa ",
                " nggênêpi = njangkêpi = - = melengkapi ",
                " nggoleki = madosi = - = mencari ",
                " nggugah = nggigah = mungu = membangunkan ",
                " nggugat = nggigat = - = menggugat ",
                " nggunakake = ngginakakên = - = menggunakan ",
                " nggêmuyu = nggêgujêng = - = menertawakan ",
                " ngilang = ngical = - = hilang ",
                " nginang = ngganten = - = menginang ",
                " nginêp = nyipêng = nyare = menginap ",
                " ngingu = ngingah = - = memelihara ",
                " nglairake = nglairakên = mbabarakên = melahirkan ",
                " nglarani = nyakiti = - = menyakiti ",
                " ngliwêt = mbêthak = - = menanak nasi ",
                " ngudarasa = ngudaraos = - = membatin ",
                " njaba = njawi = - = di luar ",
                " njaga = njagi = ngrêksa = menjaga ",
                " njagokake = nyawungakên = - = mencalonkan ",
                " njaluk = nyuwun = - = minta ",
                " nom = nem = timur = muda ",
                " nuli = nuntên, lajêng = - = lalu, cepat ",
                " nyambut gawe = nyambut damêl = ngasta damêl = bekerja ",
                " nyêkêl = nyêpêng = ngasta = memegang ",
                " nyilih = nyambut = ngampil = pinjam ",
                " nyrêngêni = - = ndukani = memarahi ",
                " nyritani = nyriyosi = - = menceritakan ",
                " nyundhuki = - = nyangsangi = menyunting ",
                " obah = ebah = - = bergerak ",
                " obat = jampi = usada = obat ",
                " obong = bêsmi = - = bakar ",
                " oleh = angsal = - = mendapatkan ",
                " omah = griya = dalêm = rumah ",
                " ombe = - = unjuk = minum ",
                " ombo = wiyar = - = luas ",
                " omong = ginêm = andika = bicara ",
                " ompong = - = dhaut = ompong ",
                " opah = epah = - = upah ",
                " ora = botên = - = tidak ",
                " owah = ewah = - = berubah ",
                " padha = sami = - = sama ",
                " padhang = pajar = - = terang ",
                " padu = pabên = - = bertengkar ",
                " paido = paibên = - = tidak percaya ",
                " pajêng = paos = - = pajak ",
                " pakarangan = pêkawisan = - = halaman ",
                " panah = - = jêmparing = panah ",
                " panas = bênter = - = panas ",
                " pangan = têdha = dhaharan = makanan ",
                " panggonan = panggenan = - = tempat ",
                " pangilon = - = paningalan = cermin ",
                " pangudakara = pangudakawis = - = perkiraan ",
                " pangudarasa = pangudaraos = - = perasaan hati ",
                " panguripan = pagesangan = - = kehidupan ",
                " papat = sêkawan = - = empat ",
                " paran = purug = - = rantau ",
                " pari = pantun = - = padi ",
                " pasa = siyam = - = puasa ",
                " pasar = pêkên = - = pasar ",
                " pati = pêjah = seda, surud = kematian ",
                " payu = pajêng = - = laku ",
                " payung = - = songsong = payung ",
                " pek = pêndhêt = pundhut = ambil ",
                " petan = - = ulik = mencari kutu rambut ",
                " pêndhapa = pêndhapi = - = pendapa ",
                " pêdhang = - = sabêt = pedang ",
                " pêndhok = kandhêlan = - = lapisan emas pada keris ",
                " pênêr = lêrês = - = tepat ",
                " pênthil = - = mundri = putting susu ",
                " piandel = kapitadosan = - = kepercayaan ",
                " pijêt = - = pêtêk = pijit ",
                " pikir = manah = pênggalih = pikiran ",
                " pikul = dipunrêmbat = - = dipikul ",
                " pilara = dipunpisakiti = - = disakiti ",
                " pilis = - = larik, sigit = pilis ",
                " ping = ping, kaping = - = dikalikan ",
                " pipi = - = pêngarasan = pipi ",
                " pira = pintên = - = berapa ",
                " piranti = pirantos = - = alat ",
                " piring = lancaran = ambêngan = piring ",
                " pisan = pindhah = - = sekali ",
                " pitakon = pitakên = padangon = apa yang ditanyakan ",
                " pitaya = pitados = - = percaya ",
                " pitik = ayam = - = ayam ",
                " pituduh = pitêdah = - = nasihat, petunjuk ",
                " pracaya = pitados = - = percaya ",
                " prada = praos = - = cat emas ",
                " prakara = prêkawis = - = perkara ",
                " prayoga = prayogi = - = patut, layak ",
                " prau = baita = - = perahu ",
                " prihatin = prihatos = - = prihatin, berprihatin ",
                " pring = dêling, bambu = - = bambu ",
                " priyayi = priyantun = - = bangsawan ",
                " puluh = dasa = - = puluh ",
                " pundhak = - = pamidangan = pundak, bahu ",
                " pungkur = pêngkêr = - = bagian / sisi belakang ",
                " pupak = - = dhaut = ganti gigi, ompong ",
                " pupu = - = wêntis = paha ",
                " pupur = - = tasik = bedak ",
                " puput = - = dhautan = putus tali pusar ",
                " pusêr = pusêr = - = pusar ",
                " putih = pêthak = - = putih ",
                " putu = - = wayah = cucu ",
                " rabi = - = krama, pikrama = nikah, kawin ",
                " rada = radi = - = agak ",
                " rahayu = rahajêng = - = selamat ",
                " rai = - = pasuryan = muka, wajah ",
                " rambut = - = rikma = rambut ",
                " rana = mrika, mriku = - = ke sana ",
                " rasa = raos = - = rasa, perasaan ",
                " rata = radin = - = rata, merata ",
                " raup = - = suryan = cici muka ",
                " rene = mriki = - = ke sini ",
                " rewang = rencang = abdi = pembantu ",
                " rêbut = rêbat = - = rebut, rampas ",
                " rêdatin = rêdatos = - = sedih, susah ",
                " rêga = rêgi = - = harga ",
                " rêkasa = rêkaos = - = sulit, parah ",
                " rêmbug = rêmbag = - = runding ",
                " rêmbulan = - = candra = bulan ",
                " ribut = ribêt = - = repot ",
                " rina = rintên = - = siang ",
                " riyak = - = jagra = lendir, dahak ",
                " riyaya = riyadi = - = hari raya ",
                " robah = rêbah = - = ubah, berubah ",
                " rokok = sês = - = rokok ",
                " rombak = rêbah, rombak = - = rombak ",
                " rubêd = ribêd = - = repot ",
                " rubuh = rêbah = - = roboh ",
                " rumat = rimat = - = simpan, pelihara ",
                " rungu = pirêng = pidangêt = dengar ",
                " runtuh = rêntah = - = runtuh ",
                " rupa = rupi = - = rupa ",
                " rupak = ripak = - = sempit pandangannya ",
                " rusak = risak = - = rusak ",
                " rusuh = rêsah = - = rusuh ",
                " sabuk = - = paningsêt = sabuk ",
                " saguh = sagah = - = sanggup ",
                " saiki = sakmênika = - = sekarang ",
                " sajen = - = caosan = sajian ",
                " saji = - = dipunsaosaken = diberikan saja ",
                " saka = saking = - = asalnya ",
                " salah = lêpat = - = salah ",
                " salin = santun, gantos = - = ganti pakaian ",
                " sambung = sambêt = - = sambung ",
                " samubarang = samukawis = - = segala sesuatu ",
                " sangga = sanggi = - = ditopang, ditanggung ",
                " sapa = sintên = - = siapa ",
                " sapi = lêmbu = - = lembu ",
                " sapih = - = dipunpêgêng = disapih, disarak ",
                " sarwa = sarwi = - = serba ",
                " sasi = wulan = - = bulan ",
                " sawah = sabin = - = sawah ",
                " seba = sowan = - = menghadap ",
                " seje = sanes = - = berbeda ",
                " seleh = sukakakên = paringaken = ditaruh, diletakkan ",
                " sendok = - = lantaran = sendok ",
                " sesuk = benjing = - = besuk ",
                " sê- = satunggal = - = satu ",
                " sêbar = dhawah = - = sebar (benih) ",
                " sêbut = sêbatan = - = nama ",
                " sêbut = sêbat = - = mengatakan, sebut ",
                " sêdhela = sakedhap = - = sebentar ",
                " sêdhêng = cêkap = - = cukup ",
                " sêdhêngan = cêkapan = - = kecukupan ",
                " sêga = sêkul = - = nasi ",
                " sêgara = sêgantên = - = laut ",
                " sêka = saking = - = dari ",
                " sêlawe = sêlangkung = - = dua puluh lima ",
                " sêmana = sêmantên = - = sekian itu ",
                " sêmaya = sêmagos = - = menangguhkan ",
                " sêmbêlih = pragat = - = menyembelih ",
                " sêmono = sêmantên = - = sebesar itu ",
                " sênêng = rêmen = - = senang, suka ",
                " sêparo = sêpalih = - = separo ",
                " sêpi = sêpên = - = sunyi, sepi ",
                " sêprana = sêprika = - = sejak dulu ",
                " sêprene = sêpriki = - = sampai sekarang ",
                " sêpuluh = sêdasa = - = sepuluh ",
                " sêru = sora = - = keras (suara) ",
                " sêtali = sêtangsul = - = dua puluh sen ",
                " sêthithik = sêkêdhik = - = sedikit ",
                " si = pun = - = si ",
                " sida = siyos = estu = jadi ",
                " siji = sêtunggal = - = satu ",
                " sikil = suku = sampeyan = kaki ",
                " sikut = - = siku = siku ",
                " silih = sambut = pundhut, ampil = pinjam ",
                " silihan = sambutan = ampilan = pinjaman ",
                " sing = ingkang = - = yang ",
                " sisi = - = sêmprit = membuang ingus ",
                " slamet = wilujeng = sugeng = selamat ",
                " slametan = wilujengan = sugengan = selamatan ",
                " sok = asring = - = sering ",
                " sore = sontên = - = sore ",
                " sranta = srantos = - = sabar menanti ",
                " srêngenge = surya = - = matahari ",
                " srêngên = - = dipunsrêngêni = dimarahi ",
                " suguh = dipunsêgah = dipunsugata = disuguh ",
                " sukêr = - = tarab = bulanan ",
                " sukêt = rumput = - = rumput ",
                " sumurup = sumêrêp = priksa, uninga = mengerti, melihat ",
                " sunat = - = têtês = khitan ",
                " sungu = singat = - = tandut ",
                " supaya = supados = - = supaya ",
                " surasa = suraos = - = arti, maksud ",
                " suruh = dipunsêdhahi = - = diundang ",
                " surup = sêrap = - = petang ",
                " susah = sisah = sêngkêl = susah ",
                " suson = sêsêpan = - = masih menyusu ",
                " susu = - = pêmbayun = susu, payudara ",
                " susur = susur = - = sugi, susur ",
                " suwara = suwanten = - = suara ",
                " suwarga = suwargi = - = surga, almarhum ",
                " suwe = dangu = - = lama ",
                " suwêng = sêngkang = - = sunbang ",
                " suwung = suwêng = - = (rumah) kosong ",
                " tai = tinja = - = tahi, tinja ",
                " tak- = kula- = dalem-, kawula- = saya ",
                " takon = taken = mundhut priksa = bertanya ",
                " tali = tangsul = - = tali ",
                " tamba = jampi = usada = obat ",
                " tampa = tampi = - = memperoleh ",
                " tanda tangan = - = tapak asta = tanda tangan ",
                " tandur = tanêm = - = tanam ",
                " tangan = - = asta = tangan ",
                " tangga = tanggi = - = tetangga ",
                " tanggon = tanggên = - = tangguh ",
                " tanggung = tangêl = - = tanggung-tanggung ",
                " tangi = - = wungu = bangun ",
                " tangis = - = pamuwun = tangis ",
                " tapêl = - = rakêtan = bedak perut ",
                " tapih = sinjang = nyamping = kain batik (perempuan) ",
                " tari, ditari = dipuntantun = - = ditanya mau atau tidak ",
                " tatu = - = labêt = luka ",
                " tau = nate = - = pernah ",
                " tawa = tawi = - = menawari dagangan ",
                " têbu = rosan = - = tebu ",
                " têgal = têgil = - = ladang ",
                " têka = dhatêng = rawuh = datang ",
                " têkan = dumugi = - = tiba, sampai ",
                " têkên = - = lantaran = tongkat ",
                " têlu = tiga = - = tiga ",
                " têmbaga = têmbagi = - = tembaga ",
                " têmbang = sêkar = - = lagu, nyanyian ",
                " têmên = estu, yêktos = - = sungguh, benar ",
                " têmon = pêpanggihan = - = pertemuan ",
                " têmu = panggih = - = temu ",
                " tênan = estu, yêktos = - = senyatanya ",
                " têpung = têpang = - = kenal, bertemu ",
                " têrus = lajêng = - = terus ",
                " têtak = supit = - = khitan ",
                " têtêpungan = têtêpangan = - = berkenalan ",
                " têtuwa = sêsêpuh = - = sesepuh, tetua ",
                " tilik = dhawah = - = jatuh ",
                " tilik = tuwi = tinjo, sowan = berkunjung, menjenguk ",
                " tinggal = tilar = - = meninggalkan ",
                " tlaten = tlatos = - = tekun ",
                " tonton = tingal = priksa = lihat ",
                " tontonan = têtingalan = - = pertunjukan ",
                " trasi = traos = - = terasi ",
                " tuduh = têdah = paring priksa = memberitahukan ",
                " tuku = tumbas = mundhut = beli ",
                " tulis = sêrat = - = tulis ",
                " tulisan = sêratan = - = tulisan ",
                " tuma = - = itik = kutu ",
                " tumbak = waos = watangan = tombak ",
                " tuna = tuni = - = rugi, tidak sampai ",
                " tunggal = tungil = - = satu, tunggal ",
                " tunggang = tumpak = nitih = naik (kendaraan) ",
                " tunggangan = tumpakan = titihan = kendaraan ",
                " tunggu = têngga = - = tunggu ",
                " turah = tirah = - = lebih ",
                " turon = tilêman = sareyan = tiduran ",
                " turu = tilem = sare = tidur ",
                " turun = têdhak = - = keturunan ",
                " turunan = têdhakan = - = asal usul keturunan ",
                " tutu = dipungêntang = - = ditumbuk ",
                " tutur = sanjang, criyos = paring priksa = berkata ",
                " tuwa = sêpuh = yuswa = tua ",
                " tuwuh = tewah = - = tumbuh ",
                " udakara = udakawis = - = kira-kira ",
                " udan = jawah = - = hujan ",
                " udhar = - = lukar = lepas kain batik ",
                " udhun = mandhap = - = turun ",
                " uga = ugi = - = juga ",
                " ugêl-ugêl = - = pagêlangan = pergelangan tangan ",
                " ujar = - = punagi = janji, sumpah ",
                " ula = sawêr = - = ular ",
                " ulat = - = pasuryan = raut muka ",
                " ulêm = - = atur = undangan ",
                " ulih = mantuk = kondur = pulang ",
                " umbêl = - = gadhing = ingus ",
                " umur = - = yuswa = umur ",
                " undang = timbal = atur = panggil ",
                " undhak = mindhak = - = meningkat ",
                " unggah = inggah = - = naik ",
                " ungkur = pêngkêr = - = belakang ",
                " uni = ungêl = - = bunyi, suara ",
                " untu = waos = waja = gigi ",
                " upakara = upakawis = - = pelihara ",
                " upama = upami = - = upama ",
                " urip = gesang = sugeng = hidup ",
                " utama = utami = - = utama ",
                " utang = sambut = ngampil = pinjam ",
                " utawa = utawi = - = atau ",
                " usus = - = jaringan = usus ",
                " uyah = sarêm = - = garam ",
                " uyuh = toyan = - = kencing ",
                " waca = waos = - = baca ",
                " wacan = waosan = - = bacaan ",
                " wadi = wados = - = rahasia ",
                " wadon = êstri = putri, wanita = putri, perempuan ",
                " wae = kemawon = - = saja ",
                " wahing = - = sigra = bersin ",
                " waja = waos = - = baja ",
                " walanda = walandi = - = belanda ",
                " wani = wantun = - = berani ",
                " wanti-wanti = wantos-wantos = - = nasehat keras ",
                " warangka = sarungan = - = sarung keris ",
                " waras = saras = waluya = sembuh ",
                " warêg = tuwuk = - = kenyang ",
                " warisan = tilaran = pusaka = warisan ",
                " warna = warni = - = warna/jenis ",
                " warung = wande = - = kedai, warung ",
                " waspada = wasapaos = - = wasapada ",
                " watara = watawis = - = antara, kira-kira ",
                " watu = sela = - = batu ",
                " watuk = - = cêkoh = batuk ",
                " wayah = wanci = - = waktu ",
                " wayang = ringgit = - = wayang ",
                " wedang = bênteran = unjukan = minuman ",
                " weneh = dipunsukani = - = diberi ",
                " wêdêl = cêlêp = - = cat kain ",
                " wêdhus = menda = - = kambing ",
                " wêktu = wêkdal = - = waktu ",
                " wêngi = dalu = - = malam ",
                " wêrta = wêrtos, wartos = - = berita, kabar ",
                " wêruh = sumêrêp = uninga, priksa = tahu, melihat ",
                " wêsi = tosan = - = besi ",
                " wêteng = padharan = - = perut ",
                " wêtu = kêwêdal = kêwiyos = terungkap ",
                " wêton = wêdalan = - = hari kelahiran ",
                " wicara = wicantên = ngêndika = bicara ",
                " wigati = wigatos = - = perlu sekali, penting ",
                " wilang = wical = - = hitung ",
                " wilangan = wicalan = - = hitungan, bilangan ",
                " wirang = isin = lingsem = malu ",
                " wis = sampun = - = sudah ",
                " wisuh = - = wijik = mencuci tangan/kaki ",
                " wong = tiyang = priyantun = orang ",
                " wuda = - = lukar = lepas pakaian ",
                " wudêl = - = nabi = pusar ",
                " wudun = - = untar = bisul ",
                " wulangan = wucalan = - = pelajaran ",
                " wuluh = wêlah = - = buluh, bambu ",
                " wuragil = - = waruju = bungsu ",
                " wurung = sande = - = tidak jadi ",
                " wutuh = wêtah = - = utuh ",
                " wuwuh = wêtah = - = bertambah ",
                " wuwuhan = wêwahan = - = tambahan ",
                " ya, iya = inggih = - = ya ",
                " yêkti = yêktos = - = betul ",
                " yen = bilih = - = jikalau "
        };

        lv = (ListView) findViewById(R.id.list_view);
        inputSearch = (EditText) findViewById(R.id.inputSearch);

        adapter = new ArrayAdapter<String>
                (this, R.layout.activity_list_item, R.id.item, item);
        lv.setAdapter(adapter);



        inputSearch.addTextChangedListener(new TextWatcher() {
            @Override
            public void onTextChanged(CharSequence cs, int arg1, int arg2, int arg3) {
                activity_satu.this.adapter.getFilter().filter(cs);
            }

            @Override
            public void beforeTextChanged(CharSequence arg0, int arg1, int arg2, int arg3) {
                //TODO Auto-generated method stub
            }

            @Override
            public void afterTextChanged(Editable arg0) {
                //TODO Auto-generated method stub
            }
        });
    }
}